import React, { useState, useRef, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { toast } from 'react-toastify';
import { ArrowLeft, CheckCircle2, ShieldAlert } from 'lucide-react';

interface PolicySection {
  id: string;
  number: number;
  title: string;
  content: string[];
}

const Policies: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [activeSection, setActiveSection] = useState<string>('terms');
  const rightPaneRef = useRef<HTMLDivElement>(null);
  const tabRefs = useRef<{ [key: string]: HTMLButtonElement | null }>({});
  const sectionRefs = {
    terms: useRef<HTMLDivElement>(null),
    privacy: useRef<HTMLDivElement>(null),
    refund: useRef<HTMLDivElement>(null),
    return: useRef<HTMLDivElement>(null),
    shipping: useRef<HTMLDivElement>(null),
  };

  const sections: PolicySection[] = [
    {
      id: 'terms',
      number: 1,
      title: 'Terms & Conditions',
      content: [
        'This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.',
        'This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://www.artopusindia.com ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform").',
        'The Platform is owned by Sasirekha creations, a company incorporated under the Companies Act, 1956 with its registered office at No 18, 12th Main Veera Sagara Main Road, Attur Layout, Yelahanka, Bengaluru - 560064 (hereinafter referred to as "Platform Owner", "we", "us", "our").',
        'Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.',
        'These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, "Services"). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.',
        'For the purpose of these Terms of Use, wherever the context so requires "you", "your" or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.',
        'ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.',
        'The use of Platform and/or availing of our Services is subject to the following Terms of Use:',
        '1. To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.',
        '2. Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.',
        '3. Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.',
        '4. The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.',
        '5. You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.',
        '6. You agree to pay us the charges associated with availing the Services.',
        '7. You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.',
        '8. You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.',
        '9. You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.',
        '10. You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney\'s fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.',
        '11. Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.',
        '12. These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.',
        '13. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Bengaluru, Karnataka, India.',
        '14. All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.'
      ]
    },
    {
      id: 'privacy',
      number: 2,
      title: 'Privacy Policy',
      content: [
        'Introduction: This Privacy Policy describes how Sasirekha creations and its affiliates (collectively "Sasirekha creations, we, our, us") collect, use, share, protect or otherwise process your information/ personal data through our website https://www.artopusindia.com (hereinafter referred to as Platform). Please note that you may be able to browse certain sections of the Platform without registering with us. We do not offer any product/service under this Platform outside India and your personal data will primarily be stored and processed in India. By visiting this Platform, providing your information or availing any product/service offered on the Platform, you expressly agree to be bound by the terms and conditions of this Privacy Policy, the Terms of Use and the applicable service/product terms and conditions, and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. If you do not agree please do not use or access our Platform.',
        'Collection: We collect your personal data when you use our Platform, services or otherwise interact with us during the course of our relationship. Some of the information that we may collect includes but is not limited to personal data / information provided to us during sign-up/registering or using our Platform such as name, date of birth, address, telephone/mobile number, email ID and/or any such information shared as proof of identity or address. Some of the sensitive personal data may be collected with your consent, such as your bank account or credit or debit card or other payment instrument information or biometric information such as your facial features or physiological information (in order to enable use of certain features when opted for, available on the Platform) etc. all of the above being in accordance with applicable law(s). You always have the option to not provide information, by choosing not to use a particular service or feature on the Platform. We may track your behaviour, preferences, and other information that you choose to provide on our Platform. This information is compiled and analysed on an aggregated basis.',
        'Usage: We use personal data to provide the services you request. To the extent we use your personal data to market to you, we will provide you the ability to opt-out of such uses. We use your personal data to assist sellers and business partners in handling and fulfilling orders; enhancing customer experience; to resolve disputes; troubleshoot problems; inform you about online and offline offers, products, services, and updates; customise your experience; detect and protect us against error, fraud and other criminal activity; enforce our terms and conditions; conduct marketing research, analysis and surveys; and as otherwise described to you at the time of collection of information.',
        'Sharing: We may share your personal data internally within our group entities, our other corporate entities, and affiliates to provide you access to the services and products offered by them. These entities and affiliates may market to you as a result of such sharing unless you explicitly opt-out. We may disclose personal data to third parties such as sellers, business partners, third party service providers including logistics partners, prepaid payment instrument issuers, third-party reward programs and other payment opted by you. These disclosures may be required for us to provide you access to our services and products, to comply with our legal obligations, to enforce our user agreement, to facilitate our marketing and advertising activities, or to prevent, detect, mitigate, and investigate fraudulent or illegal activities. We may disclose personal and sensitive personal data to government agencies or other authorised law enforcement agencies if required to do so by law.',
        'Security Precautions: To protect your personal data from unauthorised access or disclosure, loss or misuse we adopt reasonable security practices and procedures. Once your information is in our possession or whenever you access your account information, we adhere to our security guidelines to protect it against unauthorised access and offer the use of a secure server. However, the transmission of information is not completely secure for reasons beyond our control. By using the Platform, the users accept the security implications of data transmission over the internet which cannot always be guaranteed as completely secure. Users are responsible for ensuring the protection of login and password records for their account.',
        'Data Deletion and Retention: You have an option to delete your account by visiting your profile and settings on our Platform, this action would result in you losing all information related to your account. We retain your personal data information for a period no longer than is required for the purpose for which it was collected or as required under any applicable law. We may in event of any pending grievance, claims, pending shipments or any other services refuse or delay deletion of the account. Once the account is deleted, you will lose access to the account.',
        'Consent: By visiting our Platform or by providing your information, you consent to the collection, use, storage, disclosure and otherwise processing of your information on the Platform in accordance with this Privacy Policy. If you disclose to us any personal data relating to other people, you represent that you have the authority to do so and permit us to use the information. You consent to us to contact you through SMS, instant messaging apps, call and/or e-mail for the purposes specified. You have an option to withdraw your consent that you have already provided by writing to the Grievance Officer.'
      ]
    },
    {
      id: 'refund',
      number: 3,
      title: 'Refund & Cancellation Policy',
      content: [
        'This refund and cancellation policy outlines how you can cancel or seek a refund for a product / service that you have purchased through the Platform.',
        'Cancellations will only be considered if the request is made within 5 days of placing the order. However, cancellation requests may not be entertained if the orders have been communicated to such sellers / merchant(s) listed on the Platform and they have initiated the process of shipping them, or the product is out for delivery. In such an event, you may choose to reject the product at the doorstep.',
        'Sasirekha creations does not accept cancellation requests for perishable items like flowers, eatables, etc. However, the refund / replacement can be made if the user establishes that the quality of the product delivered is not good.',
        'In case of receipt of damaged or defective items, please report to our customer service team. The request would be entertained once the seller/ merchant listed on the Platform, has checked and determined the same at its own end. This should be reported within 5 days of receipt of products.',
        'In case you feel that the product received is not as shown on the site or as per your expectations, you must bring it to the notice of our customer service within 5 days of receiving the product. The customer service team after looking into your complaint will take an appropriate decision.',
        'In case of complaints regarding the products that come with a warranty from the manufacturers, please refer the issue to them.',
        'In case of any refunds approved by Sasirekha creations, it will take 7 days for the refund to be processed to you.'
      ]
    },
    {
      id: 'return',
      number: 4,
      title: 'Return Policy',
      content: [
        'We offer refund / exchange within first 3 days from the date of your purchase. If 3 days have passed since your purchase, you will not be offered a return, exchange or refund of any kind.',
        'In order to become eligible for a return or an exchange:',
        '• The purchased item should be unused and in the same condition as you received it.',
        '• The item must have original packaging.',
        '• If the item was purchased on a sale, then the item may not be eligible for a return / exchange.',
        'Further, only such items are replaced by us (based on an exchange request), if such items are found defective or damaged.',
        'You agree that there may be a certain category of products / items that are exempted from returns or refunds. Such categories of the products would be identified to you at the time of purchase.',
        'For exchange / return accepted request(s) (as applicable), once your returned product / item is received and inspected by us, we will send you an email to notify you about receipt of the returned / exchanged product. If the same has been approved after the quality check at our end, your request will be processed in accordance with our policies.'
      ]
    },
    {
      id: 'shipping',
      number: 5,
      title: 'Shipping Policy',
      content: [
        'The orders for the user are shipped through registered domestic courier companies and/or speed post only.',
        'Orders are shipped within 10 days from the date of the order and/or payment or as per the delivery date agreed at the time of order confirmation and delivering of the shipment, subject to courier company / post office norms.',
        'Platform Owner shall not be liable for any delay in delivery by the courier company / postal authority.',
        'Delivery of all orders will be made to the address provided by the buyer at the time of purchase.',
        'Delivery of our services will be confirmed on your email ID as specified at the time of registration.',
        'If there are any shipping cost(s) levied by the seller or the Platform Owner (as the case be), the same is not refundable.'
      ]
    }
  ];

  useEffect(() => {
    // Read optional tab from URL search parameters (e.g. /policies?tab=privacy)
    const tab = searchParams.get('tab');
    if (tab && ['terms', 'privacy', 'refund', 'return', 'shipping'].includes(tab)) {
      scrollToSection(tab as keyof typeof sectionRefs);
    }
  }, [searchParams]);

  useEffect(() => {
    const activeTab = tabRefs.current[activeSection];
    if (activeTab) {
      activeTab.scrollIntoView({
        behavior: 'smooth',
        block: 'nearest',
        inline: 'center',
      });
    }
  }, [activeSection]);

  const scrollToSection = (id: keyof typeof sectionRefs) => {
    setActiveSection(id);
    const targetRef = sectionRefs[id];
    if (targetRef && targetRef.current && rightPaneRef.current) {
      const topOffset = targetRef.current.offsetTop - rightPaneRef.current.offsetTop;
      rightPaneRef.current.scrollTo({
        top: topOffset,
        behavior: 'smooth',
      });
    }
  };

  // Keep track of scroll positions to update active sidebar tab dynamically
  const handleRightPaneScroll = () => {
    if (!rightPaneRef.current) return;
    const scrollContainer = rightPaneRef.current;
    const containerTop = scrollContainer.scrollTop;
    const threshold = 120; // Margin to trigger active state early

    let currentSection = activeSection;
    for (const key of Object.keys(sectionRefs)) {
      const ref = sectionRefs[key as keyof typeof sectionRefs];
      if (ref.current) {
        const offsetTop = ref.current.offsetTop - scrollContainer.offsetTop;
        if (containerTop >= offsetTop - threshold) {
          currentSection = key;
        }
      }
    }
    if (currentSection !== activeSection) {
      setActiveSection(currentSection);
    }
  };

  const handleAccept = () => {
    localStorage.setItem('policiesAccepted', 'true');
    localStorage.setItem('policiesAcceptedAt', new Date().toISOString());
    toast.success('Thank you for accepting the Terms of Service & Policies!', {
      position: 'bottom-right',
      autoClose: 3500,
    });
    navigate(-1); // Return back to where user was
  };

  const handleDecline = () => {
    toast.warning('You declined the terms. Some marketplace services may require agreement.', {
      position: 'bottom-right',
    });
    navigate('/');
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-[#111111] text-gray-900 dark:text-[#F3F4F6] relative overflow-hidden flex flex-col justify-center py-16 px-4 md:px-8 transition-colors duration-200">
      {/* Decorative Large Background Font */}
      <div className="absolute top-[10%] left-0 w-full text-center pointer-events-none select-none z-0">
        <h1 className="text-[12vw] font-black text-gray-900/[0.02] dark:text-white/[0.03] tracking-widest uppercase">
          Terms of Service
        </h1>
      </div>

      <div className="max-w-6xl mx-auto w-full relative z-10">
        {/* Back Button */}
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 text-gray-500 dark:text-gray-400 hover:text-gray-950 dark:hover:text-white mb-6 group transition-colors"
        >
          <ArrowLeft size={18} className="group-hover:-translate-x-1 transition-transform" />
          <span>Back to marketplace</span>
        </button>

        {/* Page Header */}
        <div className="text-center mb-10">
          <h2 className="text-4xl md:text-5xl font-black tracking-tight text-gray-950 dark:text-white mb-2">
            Terms of Service
          </h2>
          <p className="text-gray-500 dark:text-gray-400 text-sm max-w-lg mx-auto">
            Please read the conditions, return policies, and privacy terms before continuing.
          </p>
        </div>

        {/* Layout Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 bg-white dark:bg-[#1e1e1e] rounded-[2.5rem] border border-gray-200 dark:border-gray-800 shadow-2xl overflow-hidden p-6 md:p-10 transition-colors duration-200">
          
          {/* Left Navigation Sidebar */}
          <div className="lg:col-span-4 flex flex-col justify-between border-b lg:border-b-0 lg:border-r border-gray-200 dark:border-gray-800 pb-6 lg:pb-0 lg:pr-8">
            <div className="flex flex-row overflow-x-auto whitespace-nowrap gap-2 pb-4 lg:pb-0 lg:flex-col lg:space-y-2 scrollbar-thin scrollbar-thumb-logo-purple/35">
              {sections.map((sec) => {
                const isActive = activeSection === sec.id;
                return (
                  <button
                    key={sec.id}
                    ref={(el) => { tabRefs.current[sec.id] = el; }}
                    onClick={() => scrollToSection(sec.id as keyof typeof sectionRefs)}
                    className={`shrink-0 text-left px-5 py-3 lg:py-4 rounded-2xl font-bold transition-all flex items-center justify-between gap-3 group ${
                      isActive
                        ? 'bg-logo-purple/10 text-logo-purple border border-logo-purple/20'
                        : 'text-gray-600 dark:text-gray-400 hover:text-logo-purple dark:hover:text-white hover:bg-gray-100 dark:hover:bg-white/[0.02] border border-transparent'
                    }`}
                  >
                    <span className="flex items-center gap-3">
                      <span className={`text-xs px-2 py-1 rounded-md font-black ${
                        isActive ? 'bg-logo-purple text-white' : 'bg-gray-200 dark:bg-gray-800 text-gray-500 dark:text-gray-400'
                      }`}>
                        {sec.number}
                      </span>
                      <span>{sec.title}</span>
                    </span>
                    <span className={`hidden lg:inline text-lg transition-transform ${
                      isActive ? 'translate-x-0' : 'opacity-0 group-hover:opacity-100 group-hover:translate-x-1'
                    }`}>
                      →
                    </span>
                  </button>
                );
              })}
            </div>

            <div className="hidden lg:block mt-8 p-5 bg-gray-50 dark:bg-white/[0.01] rounded-2xl border border-gray-200 dark:border-gray-800/60">
              <div className="flex gap-3 items-start">
                <ShieldAlert className="text-logo-purple shrink-0 mt-0.5" size={18} />
                <div>
                  <p className="text-xs font-bold text-gray-950 dark:text-white mb-1">Legal Binding</p>
                  <p className="text-[11px] text-gray-500 dark:text-gray-400 leading-relaxed">
                    By clicking Accept, you consent to the terms governed under the Indian Information Technology Act, 2000.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Right Scrollable Content Pane */}
          <div className="lg:col-span-8 flex flex-col h-[55vh] lg:h-[60vh] justify-between">
            <div
              ref={rightPaneRef}
              onScroll={handleRightPaneScroll}
              className="flex-1 overflow-y-auto pr-4 space-y-12 custom-scrollbar scroll-smooth"
              style={{
                scrollbarWidth: 'thin',
                scrollbarColor: '#8b5cf6 transparent',
              }}
            >
              {sections.map((sec) => (
                <div
                  key={sec.id}
                  ref={sectionRefs[sec.id as keyof typeof sectionRefs]}
                  className="space-y-4 pt-4"
                >
                  <h3 className="text-2xl font-black text-logo-purple flex items-center gap-2">
                    <span>{sec.number}.</span>
                    <span>{sec.title}</span>
                  </h3>
                  <div className="space-y-4 text-gray-600 dark:text-gray-300 text-sm leading-relaxed font-medium">
                    {sec.content.map((para, pIdx) => (
                      <p key={pIdx}>{para}</p>
                    ))}
                  </div>
                </div>
              ))}
            </div>

            {/* Action Buttons Section */}
            <div className="border-t border-gray-200 dark:border-gray-800 pt-6 mt-6 flex flex-col sm:flex-row gap-4 items-center justify-between">
              <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
                <CheckCircle2 className="text-logo-purple" size={16} />
                <span>Last Updated: July 2026</span>
              </div>
              <div className="flex gap-4 w-full sm:w-auto">
                <button
                  onClick={handleDecline}
                  className="flex-1 sm:flex-initial px-8 py-3.5 border border-logo-purple/40 hover:border-logo-purple text-logo-purple hover:bg-logo-purple/5 font-bold rounded-2xl transition-all"
                >
                  Decline
                </button>
                <button
                  onClick={handleAccept}
                  className="flex-1 sm:flex-initial px-10 py-3.5 bg-logo-purple hover:bg-logo-purple/90 text-white font-black rounded-2xl shadow-lg shadow-logo-purple/10 transition-all hover:-translate-y-0.5"
                >
                  Accept
                </button>
              </div>
            </div>

          </div>

        </div>
      </div>
    </div>
  );
};

export default Policies;
